name = "NNME"
author = "Neddimus Maximus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9662cda43bb3183fb419ad19eb90545fa0010fc18596cdbbf66510e55ee98661"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
